docs/faq: document possible filesystem incompatibility with ext4
rauc/rauc pull request #1192
Opened 2023-07-23 14:03 UTC by jluebbe

Fixes: #1190

2023-07-23 15:24 UTC, obbardc requested changes

2023-07-23 15:24 UTC, obbardc commented on docs/faq.rst
> +(perhaps build using kirkstone or older), that version of ``resize2fs`` will
```suggestion
(perhaps built using kirkstone or older), that version of ``resize2fs`` will
```

2023-07-24 09:17 UTC, jluebbe commented on docs/faq.rst
> +(perhaps build using kirkstone or older), that version of ``resize2fs`` will
Thanks, I've applied the change.

2023-07-24 18:49 UTC, Bastian-Krause approved these changes
Looks good!

2023-07-25 06:54 UTC, merged