docs/integration: recommend using stable paths in fstab and system.conf
rauc/rauc pull request #1271
Opened 2023-10-24 14:58 UTC by jluebbe

Fixes: #1149

2023-10-24 15:59 UTC, obbardc approved these changes

2023-10-24 19:43 UTC, ejoerns requested changes

2023-10-24 19:43 UTC, ejoerns commented on docs/integration.rst
> +  should normally use stable paths to refer to the partitions or devices.
```suggestion
  should normally use stable paths to refer to partitions or devices.
```

2023-10-24 19:43 UTC, ejoerns commented on docs/integration.rst
> +  Especially a filesystem UUIDs (``UUID=<uuid>`` or
```suggestion
  Especially filesystem UUIDs (``UUID=<uuid>`` or
```

2023-10-24 19:43 UTC, ejoerns commented on docs/integration.rst
> +    using the same disk image on i.e. eMMC & SD)
```suggestion
  * partition-table-UUID-based symlinks: ``/dev/disk/by-partuuid/…`` (breaks if
    using the same disk image on e.g. both eMMC & SD card)
```

2023-10-24 19:43 UTC, ejoerns commented on docs/integration.rst
> +  * plain device names: ``/dev/sda``, ``/dev/mmcblk0p1``, ``/dev/nvme0n1p1``, ``/dev/mapper/…``
Should we mention that these may depend on storage enumeration order in some cases?

2023-10-25 11:53 UTC, ejoerns approved these changes

2023-10-25 11:53 UTC, merged