contrib: rauc-client: simple update service for rauc
rauc/rauc pull request #1460
Opened 2024-07-11 10:20 UTC by angeloc

This service implements a simple remote update service for rauc. The service will check at time or intervals if there is a new release available on the select update channel url. If the version is newer of the current installed version, it calls `rauc install` to install the update and reboot.

The service is simple enough to be compatible with busybox posix shell and can be easily integrated in any environment. It depends only on curl and posix shell.

2024-07-18 13:04 UTC, jluebbe requested changes
Our plan is to have a simple update loop like this in RAUC itself (see #1114), so I'd only merge this with a disclaimer that it is an example and should not be used in production.

2024-07-19 07:46 UTC, angeloc commented on contrib/rauc-client/rauc-client
> +}
Thanks for the review!

Indeed this is far better option, and I think I implemented all of your requested changes.

2024-07-19 10:00 UTC, angeloc commented
@jluebbe out of curiosity: if this serve were written in C using the rauc coding standard, could it be suggested to use in produciont? What I mean, is posix shell the problem? If it is, I can work on a properly written client.

2024-07-19 11:14 UTC, jluebbe commented
> @jluebbe out of curiosity: if this client were written in C using the rauc coding standard, could it be suggested to use in production? What I mean, is posix shell the problem? If it is, I can work on a properly written client.

It should be part of the RAUC service itself (see the two open points in https://github.com/rauc/rauc/issues/1114). Some additional information would be needed in the manifest. Also, the service would need a state machine or something similar.

2024-07-19 12:14 UTC, angeloc commented
> It should be part of the RAUC service itself (see the two open points in #1114).

I see, awesome! I'd like to work on that, it cover perfectly my use case.

I'm thinking starting small, just something that has few configuration options, polling the remote url, download and install the update if the version is higher.
Later we can add the update checking mechanism, the remote API call and all the things.

Could that be ok?

2024-08-29 15:19 UTC, ejoerns approved these changes
Successfully tested the script locally. With the disclaimer added it's fine from my side at least.

Should be removed however as soon as we have a built-in solution.

2024-09-04 08:47 UTC, angeloc commented
@jluebbe did you find the time to write down the design for built-in mechanism?

2024-09-05 15:37 UTC, jluebbe approved these changes

2024-09-05 15:37 UTC, merged

2024-09-06 06:59 UTC, jluebbe commented
> @jluebbe did you find the time to write down the design for built-in mechanism?

See [my comment in #1114](https://github.com/rauc/rauc/issues/1114#issuecomment-2332240262).

2024-09-06 07:00 UTC, jluebbe commented
> @jluebbe did you find the time to write down the design for built-in mechanism?

@angeloc, see [my comment in #1114](https://github.com/rauc/rauc/issues/1114#issuecomment-2332240262).