update compiler warning configuration
rauc/rauc pull request #1469
Opened 2024-07-18 18:57 UTC by jluebbe

Add some more useful warnings and allow declarations after statements. This makes is easier to declare (temporary) variables where they are
initialized. Together with g_auto*, this makes code easier to read.

2024-07-18 21:02 UTC, ejoerns requested changes

2024-07-18 21:02 UTC, ejoerns commented on meson.build
> +  -Wdangling-pointer
Covered by `-Wall` already (meson `warning_level=2`).

2024-07-18 21:40 UTC, jluebbe commented
Instead of checking multiple compilers (and rechecking on updates), I'd tend to err on the side of having some options already covered by -Wall/-Werror in the list.

2024-07-18 21:53 UTC, ejoerns commented
> Instead of checking multiple compilers (and rechecking on updates), I'd tend to err on the side of having some options already covered by -Wall/-Werror in the list.

Maybe it's a better option to describe than how the options to enable are selected? Otherwise, this also looks a bit 'random' and might not be easier to maintain in the end. One could manually enable all GCC `-Wall` options and have it look like a stricter checking.

I'm highly unsure about what's a good strategy if not only looking at GCC. Thus if you find the approach to enable checks based on personal heuristics the most promising, I'd tend to comply.

2024-07-19 12:10 UTC, jluebbe commented on meson.build
> +  -Wcast-align=strict
`-Wcast-align=strict` may be unsupported even if `-Wcast-align` works.

2024-07-19 12:14 UTC, jluebbe commented on meson.build
> +  -Wint-conversion
I'm not sure and would tend to enable it explicitly.

2024-07-19 12:27 UTC, merged