add support for composefs artifacts
rauc/rauc pull request #1500
Opened 2024-08-14 16:00 UTC by jluebbe

Based on #1301, add support for composefs artifacts.

2024-11-21 14:09 UTC, ejoerns requested changes

2024-11-21 14:09 UTC, ejoerns commented on src/artifacts_composefs.c
> +gboolean r_artifact_repo_prepare_composefs(RArtifactRepo *repo, GError **error)
Function names do not really match the module name, but maybe at least use consistent prefixes?

`r_composefs_artifact_*` vs `r_artifact_repo_..._composefs`

2024-11-25 17:02 UTC, jluebbe commented on src/artifacts.c
> +			g_error("Image '%s/%s' has supported format for repo type '%s'",
This can happen when the input manifest uses an invalid conversion for a given repo type.

2024-11-25 17:05 UTC, jluebbe commented on src/bundle.c
> +	converted_image_path = g_build_filename(converted_path, "image", NULL);
In the future, this directory could contain other files, such as a signature over a fsverity hash.

2024-11-25 17:24 UTC, jluebbe commented on src/artifacts_composefs.c
> +	g_info("Removed %d unused objects in local object store", removed);
Yes, I though it useful to see that cleanup is working.

2024-11-25 19:43 UTC, ejoerns commented on src/bundle.c
> +	converted_image_path = g_build_filename(converted_path, "image", NULL);
Okay, but I'd still expect the image to have the `.cfs` suffix rather than the directory.

2025-01-24 08:54 UTC, jluebbe commented on src/bundle.c
> +	converted_image_path = g_build_filename(converted_path, "image", NULL);
The bundles now have `foo.tar.cfs/image.cfs`.

2025-01-24 08:56 UTC, jluebbe commented on src/artifacts_composefs.c
> +			g_propagate_prefixed_error(error, ierror, "failed to copy object: ");
I used `"Failed to copy composefs object from bundle to local store: "`.

2025-01-24 09:16 UTC, jluebbe commented on src/bundle.c
> +			if (g_strv_contains((const gchar * const *)image->convert, "composefs"))
I've made it optional.

2025-02-06 07:40 UTC, ejoerns commented on src/artifacts.c
> +			g_error("Image '%s/%s' has supported format for repo type '%s'",
So it should not be a `g_error()`. Fixed it.

2025-02-06 07:41 UTC, ejoerns commented on src/bundle.c
> +			} else if (g_str_equal(*method, "composefs")) {
When RAUC is compiled without composefs support, this conversion method will fail. I've made this explicit now.

2025-02-06 07:45 UTC, ejoerns requested changes
I've fixed and pushed a few usage issues I've found: https://github.com/rauc/rauc/compare/3235d74924c8403db90c4a267ed5d571b2866ef5..f337a0e28855c80f855be87ac1a3b7fa17c091da
Please check if you agree with them.

The rest looks fine to me now.

Please rebase the PR onto `master` to resolve the file conflicts.

2025-02-07 09:01 UTC, jluebbe commented
Thanks for the fixes. Rebased on master.

2025-02-07 11:05 UTC, ejoerns approved these changes

2025-02-07 11:07 UTC, merged