support locating system.conf in /usr and /run
rauc/rauc pull request #1557
Opened 2024-11-14 20:36 UTC by a3f

Traditionally, programs look up their configuration in /etc and this is
also what RAUC has been doing so far.

The modern pattern is to consult configuration files at a number of
locations. The default distro-provided config goes into /usr/lib,
which may be even read-only.

A runtime override is possible by placing a configuration into /run,
which masks the distro-provided config. The old location in /etc becomes
the highest priority override and is left to the system administrator.

Putting RAUC along with its configuration into /usr is called hermetic
/usr. The search path order implemented here is the recommendation
described in this patch is aligned with the UAPI group's Configuration
Files Specification[1].

The specification goes beyond what is implemented here and describes
also support for drop-in extensions to the configuration files.

This involves more work, because GKeyFile doesn't support merging of
config files, so drop-in support is skipped for now.

[1]: https://uapi-group.org/specifications/specs/configuration_files_specification/

---

Fixes: #1252

- What do you use the feature for?

/usr/lib/rauc/system.conf is the default config and I override it in /run or /etc for select boards.

- How does RAUC benefit from the feature?

The maintainers already indicated in #1252 that they want to support hermetic /usr.

- How did you verify the feature works?

RAUC now prints e.g. `Using system config file /run/rauc/system.conf`. I removed files or broke symlinks and verified that the search path is used in the intended order.

2024-11-15 14:07 UTC, jluebbe requested changes
Looks good otherwise.

2024-11-15 14:57 UTC, a3f commented on README.rst
> +Create a system configuration file in ``/usr/lib/rauc/system.conf`` and start the
Given that this is the README, I just left it as /etc.

2024-11-15 20:25 UTC, ejoerns approved these changes

2024-11-15 20:26 UTC, merged

2024-11-16 15:10 UTC, evelikov commented
Glancing at `load_config()` it's not immediately obvious if this work correctly if the file is a symlink to `/dev/null`? Both wrt reading the file contents (`g_file_get_contents()`) and the resolving the path (`resolve_path_take()` aka `g_path_get_dirname()`.

Mind you my glib is somewhat ... limited :sweat_smile:

2024-11-16 17:11 UTC, a3f commented
@evelikov I originally came to the conclusion that the config masking doesn't make sense for the RAUC, because

 * the target operations of RAUC (e.g. bundle installation, status mark-good) can't happen without a config, so whether we have no config or an empty config, the operation would fail anyway and no default config could remedy this
 * the host operations of RAUC use a default config and don't bother with reading a file anyway.

So as long we don't have snippets, the masking doesn't buy us anything.

Revisiting it now, I see that there is indeed a case where it matters: `rauc extract` & `rauc info`. These check for a config, but have an automatic fallback to the default config. The correct behavior would thus be that a symlink to /dev/null (or an empty file) would trigger fallback to the default config directly, whereas currently it probably ends up with a failure.

I will look into implementing this next week.