Add option to prevent fallback
rauc/rauc pull request #1584
Opened 2024-12-11 14:47 UTC by N3xp7im3

This PR aims to implement an option that automatically marks all _other_ slots as bad when the booted one is marked as good. This can be used to ensure not booting into the previous used slot after installing a new rootfs. The option is called "prevent-fallback" and can be set in the _system_ section.

For example:

```
    [system]
    compatible=My BSP
    bootloader=barebox
    bundle-formats=-plain
    data-directory=/data/rauc
    prevent-fallback=true
    ....
```

The main logic for this patch is mostly based on the underlying "mark-bad other" command.
In order to make the prevent-fallback option to work for more than two slots, I have reworked the _get_slot_by_identifier_ function to be able to return more than one slot.

For the test case I decided to only test the "mark-bad other" command as the prevent-fallback option simply calls this command. I used the ABC pytest fixture from [38f7a2f8eac](https://github.com/rauc/rauc/commit/38cb2e4b4aed8ad1a5c5f1af0884938f7a2f8eac) for my test.

There is one minor issue with this PR, which is the message handling in the _mark_run_ function. When the fallback option is enabled, we call the _mark_run_ method recursively which results in overriding the variables _message_ and _slot_name_. This results in information loss as only the last call  sets the variables properly. One possible solution to fix this is by concatenating the messages and slot_names in some way?

2024-12-12 17:31 UTC, jluebbe requested changes

2024-12-12 17:31 UTC, jluebbe commented on src/mark.c
> +			*slot_name = g_strdup("other");
Previously, this was set to the actual "resolved" name of the other slot. Accordingly, this should probably use the space separate slot names.

See below for a simpler solution to handle `slot_name`.

2024-12-12 17:31 UTC, jluebbe commented on src/mark.c
> -		*slot_name = g_strdup(slot->name);
With the new code, we only get here in the successful case. As `slot_name` should be set only then, you should be able to reduce complexity and code duplication by generating the space-separated string here only once at the end. That would move that part of the loop code in the "bad" case here.

2024-12-12 17:31 UTC, jluebbe commented on src/mark.c
> +		*message = g_strdup_printf("marked slot %s as good", slot->name);
This string overwritten in the prevent-fallback case. Move it into an `else` branch below.

2024-12-12 17:31 UTC, jluebbe commented on test/test_mark.py
> +def test_status_mark_bad_other(rauc_dbus_service_with_system_abc):
Also add a test case for the `mark-good booted` with enabled `prevent-fallback`. You can use the `system` fixture to update the config and write it again from the test case.

2025-01-20 11:34 UTC, jluebbe commented
This needs to be rebased when #1601 is merged.

2025-01-20 13:42 UTC, jluebbe commented
I had factored out the switch to `g_auto*` in mark_run in https://github.com/rauc/rauc/pull/1600.

2025-01-20 13:44 UTC, jluebbe approved these changes
I've rebased this on my PRs #1600 and #1601 to make this easier to review and test. Compared to the last version, we now have a test which runs `mark-good` with enabled `prevent-late-fallback` (which is the new name we agreed on internally).

2025-01-25 18:26 UTC, ejoerns approved these changes

2025-01-25 18:26 UTC, merged