src/bundle: download temporary bundle to a separate temp directory
rauc/rauc pull request #820
Opened 2022-01-05 08:28 UTC by jluebbe

This protects against the issue described in #819.

2022-01-05 08:38 UTC, a3f requested changes

2022-01-05 08:38 UTC, a3f commented on src/bundle.c
> +		ibundle->path = g_build_filename(g_dir_make_tmp("rauc-XXXXXX", NULL), "download.raucb", NULL);
Leaks.

2022-01-05 08:40 UTC, a3f commented on src/bundle.c
> +		ibundle->path = g_build_filename(g_dir_make_tmp("rauc-XXXXXX", NULL), "download.raucb", NULL);
And while at it, you may want to check for `NULL` and return, even if the error is unlikely.

2022-01-05 11:55 UTC, a3f submitted a review, later dismissed
LGTM. Nitpick: Code always sets `res = FALSE` in error case, even if res hasn't been changed from initial value. (See `if (verify` branch above). It might be good to follow this scheme. Makes code more robust against future refactoring.

2022-01-05 12:13 UTC, a3f submitted a review, later dismissed

2022-01-05 12:38 UTC, ejoerns commented
With this change, the tmdir is created but (unlike the bundle itself) not removed after installation/error.

2022-01-06 12:34 UTC, ejoerns approved these changes
Code changes look fine for me now.

2022-01-06 13:31 UTC, ejoerns approved these changes

2022-01-10 10:10 UTC, merged