CHANGES: prepare for 1.6 release
rauc/rauc pull request #831
Opened 2022-01-27 14:45 UTC by jluebbe

This collects the changes since the 1.5.1 release.

2022-01-27 22:39 UTC, ejoerns requested changes

2022-01-27 22:39 UTC, ejoerns commented on CHANGES
> +.. rubric:: Bug fixes
I found these two bug fixes from my pr #645 worth mentioning as I've seen myself and others hitting this multiple times:

* Fixed an issue with slots boot status determination that could accidentally mark 'good' slots as 'bad'
* Fixed emitting inconsistent slot status vie D-Bus API

2022-01-28 08:36 UTC, jluebbe commented on CHANGES
> +* Fixed missing file descriptor closing in some error cases.
Ah, I lost the authorship info in the commit during rebase. Added here.

2022-01-28 08:46 UTC, ejoerns approved these changes

2022-01-28 08:49 UTC, merged