add support for a shared data directory
rauc/rauc pull request #925
Opened 2022-06-17 07:46 UTC by jluebbe

This will be useful to keep some data across installations, which is useful for casync/desync index files or custom hash indices for incremental updates.

If no explicit path is given for the status file, it will be placed as `central.raucs` in this data directory.

2022-07-19 17:10 UTC, ejoerns requested changes
From the commit messages and the comments in code I do not fully get the intention of the hash-based directory creation and how these are to be used.

Maybe this should go into the commit where it is actually used or requires a bit better explanation of its purpose.

2022-07-19 17:10 UTC, ejoerns commented on include/slot.h
> +void r_slot_clean_data_directory(const RaucSlot *slot);
For me, the function name does not match well with what it does.

Maybe something like `r_slot_cleanup_checksum_data_directories()`?

2022-07-20 09:56 UTC, jluebbe commented on include/slot.h
> + * subdirectory in <slot data directory>/hash-<hash value>.
No, it looks like this
```
/srv/rauc
|-- central.raucs
|-- slot.rootfs.0
|   `-- hash-c5513541a59099860e3c9b3d9afbc7a3dfbde242a39159ff6d4249fcba0aba1b
|       `-- block-hash-index
`-- slot.rootfs.1
    `-- hash-be9365c22108b43dce29161e77dd3a63d12f0da09bef2c5bb0bd18de083087e1
        `-- block-hash-index

```

2022-07-20 10:05 UTC, ejoerns commented on include/slot.h
> + * subdirectory in <slot data directory>/hash-<hash value>.
Yes. Assuming that `block-hash-index` (which does not exist in this patch, yet) is a file, there is no subdirectory *in* `<slot data directory>/hash-<hash value>`. The wording is at least a little misleading I would say.

``` diff
- * To allow cleanup of data that corresponds to a specific image hash, we use a
- * subdirectory in <slot data directory>/hash-<hash value>.
+ * To allow cleanup of data that corresponds to a specific image hash, we use a
+ * `hash-<hash value>/` subdirectory in <slot data directory>/.
```

2022-07-20 10:08 UTC, ejoerns commented on include/slot.h
> +void r_slot_clean_data_directory(const RaucSlot *slot);
My impression was that it should only clean older hash dirs since it explicitly skips other files/subdirectories.

2022-07-20 12:02 UTC, jluebbe commented on src/slot.c
> +	g_return_val_if_fail(error, NULL);
Yes, but it should still return NULL.

2022-07-20 12:12 UTC, ejoerns commented on src/slot.c
> +	g_return_val_if_fail(error, NULL);
Oups, copy+pasted the wrong example line indeed :see_no_evil:

2022-07-20 13:28 UTC, ejoerns commented on docs/reference.rst
> +  * status per slot and no shared data directory
Actually, it maybe wasn't fully appropriate before. But should at least be now with changing to the term `per-slot status` that we consistently use with a hyphen.

2022-07-20 13:47 UTC, jluebbe commented on src/slot.c
> +	if (checksum) {
I'm not sure. Other functions in this file already use the braces style. I'd tend to use braces for new code as it avoid a potential mistake lateron.

2022-07-20 14:36 UTC, ejoerns approved these changes
:+1:

2022-07-20 15:26 UTC, merged