Add casync tests and remove 'experimental' note from docs
rauc/rauc pull request #957
Opened 2022-08-25 21:16 UTC by ejoerns

Docs where saying casync support is still experimental. While casync was always basically working, this disclaimer was mainly added due to missing test coverage for casync-related code.

Add the missing tests and update the documentation.

Based on #956

2022-08-26 08:55 UTC, jluebbe commented
I've rebased it on master, as #956 is merged.

2022-08-26 15:19 UTC, jluebbe requested changes
I'll also push minor wording edits in the docs.

2022-08-28 15:43 UTC, ejoerns commented on test/update_handler.c
> +		r_context_conf()->install_info->mounted_bundle->storepath = storepath;
I've added freeing of the bundle struct to the already-existing cleanup handling

2022-08-28 16:01 UTC, ejoerns commented on test/update_handler.c
> +	/* FIXME: only works with "--without=sec-time" set for "casync make"*/
Not fully unsupported but It seems that it requires at least adding `casync-args="--without=sec-time"` to the `rauc convert` call.
I have not investigated much deeper than to the casync `src/cadecoder.c` line

``` c
if (timespec_to_nsec(st.st_mtim) / granularity != read_le64(&child->entry->mtime) / granularity) 
        return -EOPNOTSUPP;
```

that is responsible for the quite imprecise casync error message

    Failed to run synchronizer: Operation not supported

2022-09-29 15:21 UTC, merged

2022-09-29 15:22 UTC, jluebbe reviewed
The bundle struct cleanup was added. Otherwise the changes were just a rebase.